gpu_id: 0
multi_gpus: True
num_workers: 4
seed: 666
exp_name: 'expTGIF-QAAction_Resnet_VLAD'

train:
  lr: 0.0001
  batch_size: 32
  restore: False
  max_epochs: 50
  word_dim: 300
  motion_dim: 2048 #1024
  appearance_dim: 2048 #1536
  module_dim: 512
  glove: True

val:
  flag: True

test:
  test_num: 0
  write_preds: False

dataset:
  name: 'tgif-qa'
  question_type: 'action'
  data_dir: 'data/tgif-qa/action'
  save_dir: 'results/'
  appearance_feat: '{}_{}_appearance_feat_resnet.h5'
  motion_feat: '{}_{}_motion_feat_resnetxt.h5'
  appearance_dict: '{}_action_resnet_appearance_feat_dict_512.h5'
  motion_dict: '{}_action_resnetxt_motion_feat_dict_512.h5'